Sistema_Iglesia/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from apps.persona import views
from apps.ministerio import views
from apps.usuario import views
from apps.evento import views
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from apps.usuario.views import RegistroUsuario

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^persona/', include('apps.persona.urls', namespace='persona')),
    url(r'^matrimonio/', include('apps.persona.urls', namespace='matrimonio')),
    url(r'^movimiento/', include('apps.movimiento_dinero.urls', namespace='movimiento')),
    url(r'^categoria/', include('apps.movimiento_dinero.urls', namespace='categoria')),
    url(r'^ministerio/', include('apps.ministerio.urls', namespace='ministerio')),
    url(r'^evento/', include('apps.evento.urls', namespace='evento')),
    url(r'^articulo/', include('apps.inventario.urls', namespace='articulo')),
    url(r'^unidad_de_medida/', include('apps.inventario.urls', namespace='unidad_de_medida')),
    url(r'^entrada/', include('apps.entrada.urls', namespace='entrada')),
    url(r'^salida/', include('apps.salida.urls', namespace='salida')),
    url(r'^usuario/', include('apps.usuario.urls', namespace='usuario')),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    #url(r'^password/recovery/',
	#	RegistroUsuario.as_view(
	#		template_name='restration/password_reset_form.html',
	#		email_template_name='restration/password_reset_email.html',
	#	),
	#	name='password_reset',
	#	),
    url(r'^reset/password_reset', password_reset,
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),

    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),

    url(r'^password/recovery/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),

    # url(
    #    r'^password/recovery/(?P<uidb64>[0-9A-Za-z_\-]+)/'
    #    r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #    auth_views.PasswordResetConfirmView.as_view(
    #        success_url=reverse_lazy('home'),
    #        post_reset_login=True,
    #        template_name='registration/password_reset_confirm.html',
    #        post_reset_login_backend=(
    #            'django.contrib.auth.backends.AllowAllUsersModelBackend'
    #        ),
    #    ),
    #    name='password_reset_confirm',
    #),

    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),



]

apps/inventario/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login_required

from apps.inventario.views import index_articulo, ArticuloList, ArticuloCreate, ArticuloUpdate, \
	ArticuloDelete, articulo_view, articulo_list, articulo_edit, articulo_delete, \
	Unidadad_de_MedidaList, Unidadad_de_MedidaCreate, Unidadad_de_MedidaUpdate, Unidadad_de_MedidaDelete, unidad_de_medida_view, unidad_de_medida_list, unidad_de_medida_edit, unidad_de_medida_delete

urlpatterns = [
    url(r'^index$', index_articulo),
    url(r'^articulo/listar$', login_required(ArticuloList.as_view()), name='articulo_listar'),
    url(r'^articulo/nueva$', login_required(ArticuloCreate.as_view()), name='articulo_crear'),
    url(r'^articulo/editar/(?P<pk>\d+)$', login_required(ArticuloUpdate.as_view()), name='articulo_editar'),
    url(r'^articulo/eliminar/(?P<pk>\d+)$', login_required(ArticuloDelete.as_view()), name='articulo_eliminar'),
	url(r'^nuevo_unidad_de_medida$',login_required(Unidadad_de_MedidaCreate.as_view()), name='unidad_de_medida_crear'),
    url(r'^listar_unidad_de_medida$', login_required(Unidadad_de_MedidaList.as_view()), name='unidad_de_medida_listar'),
    url(r'^editar_unidad_de_medida/(?P<pk>\d+)/$', login_required(Unidadad_de_MedidaUpdate.as_view()), name='unidad_de_medida_editar'),
    url(r'^eliminar_unidad_de_medida/(?P<pk>\d+)/$', login_required(Unidadad_de_MedidaDelete.as_view()), name='unidad_de_medida_eliminar'),

]

apps/persona/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from apps.persona.views import PersonaCreate,PersonaList,PersonaUpdate,PersonaDelete,index, persona_view, persona_list, persona_edit, persona_delete, \
MatrimonioList, MatrimonioCreate, MatrimonioUpdate, MatrimonioDelete, matrimonio_view, matrimonio_list, matrimonio_edit, matrimonio_delete


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$',login_required(PersonaCreate.as_view()), name='persona_crear'),
    url(r'^listar$', login_required(PersonaList.as_view()), name='persona_listar'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(PersonaUpdate.as_view()), name='persona_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required(PersonaDelete.as_view()), name='persona_eliminar'),
    url(r'^nuevo_matrimonio$',login_required(MatrimonioCreate.as_view()), name='matrimonio_crear'),
    url(r'^listar_matrimonio$', login_required(MatrimonioList.as_view()), name='matrimonio_listar'),
    url(r'^editar_matrimonio/(?P<pk>\d+)/$', login_required(MatrimonioUpdate.as_view()), name='matrimonio_editar'),
    url(r'^eliminar_matrimonio/(?P<pk>\d+)/$', login_required(MatrimonioDelete.as_view()), name='matrimonio_eliminar'),
]

templates/unidad_de_medida/unidad_de_medida_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar el registro {{ object.nombre_unidad }}?</h3>
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-default" href="{% url 'unidad_de_medida:unidad_de_medida_listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/unidad_de_medida/unidad_de_medida_form.html
{% extends 'base/base.html' %}

{% block title %}
	Alta Unidad de Medida
{% endblock %}

{% block content %}
<div class="mb-2">
<form method="post">
	{% csrf_token %}
	{% include 'includes/form.html' %}
	<button class="btn btn-default" type="submit">Registrar</button>
	<a class="btn btn-default" href="{% url 'persona:index' %}">Cancelar</a>



</form>
</div>
{% endblock %}

{% block extrajs %}
{% endblock %}

templates/unidad_de_medida/unidad_de_medida_list.html
{% extends 'base/base.html' %}
{% block title %}
	Listado de Unidades de Medida
{% endblock %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>Nombre Unidad de Medida</td>

		</tr>
	</thead>
	<tbody>
		{% if object_list %}
		{% for p in object_list %}
		<tr>
			<td>{{ p.nombre_unidad }}</td>


			<td>
				<a class="btn btn-primary" href="{% url 'unidad_de_medida:unidad_de_medida_editar' p.id%}">Editar</a>
				<a class="btn btn-danger" href="{% url 'unidad_de_medida:unidad_de_medida_eliminar' p.id%}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay Unidades de Medida Registradas</h1>
		{% endif %}
	</tbody>
</table>
<ul class="pager">
	<li>
		{% if page_obj.has_previous %}
       	 <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>

		{% endif %}
  </li>
	<li>
		{% if page_obj.has_next %}
     	 <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>

    	{% endif %}
  </li>
</ul>
{% endblock%}